### ISSUE TITLE
One output layer

### ISSUE THREAD

**Issue by Riwexoyd** [SciSharp/Keras.NET#107]
In [Model.cs](https://github.com/SciSharp/Keras.NET/blob/master/Keras/Models/Model.cs#L52), one output layer is passed as an argument.
`PyInstance = Instance.keras.models.Model(inputList, outputList[0]);` 

It is correct ?

**Comment by deepakkumar1984** [comment]
Yes, are you facing any issue with this?

**Comment by deepakkumar1984** [comment]
Please open another issue with exception details in case not solved.
