### ISSUE TITLE
Keras.Net in Unity - Dllnotfoundexception 

### ISSUE THREAD

**Issue by krishnanpc** [SciSharp/Keras.NET#109]
<img width="1159" alt="Screen Shot 2020-04-06 at 12 19 55 PM" src="https://user-images.githubusercontent.com/3471153/78548381-00168e00-7801-11ea-8042-934d182b4aba.png">

I am trying to install Keras.net for Unity, and here is the error that I get when I run the line
`var model = new Sequential();`and it is not able to get the current Python path.

Think it is related to issue #104 .

I have MacOS High Sierra, Unity 2019, Python 3.7 (Anaconda). I tried setting the path
`Environment.SetEnvironmentVariable("PYTHONHOME",`
and 
` PythonEngine.PythonHome = pythonPath;`but it is not working.

If I do  `$echo ` the path in the terminal, the path is correctly set, but however when I ask for a GetEnvironment within the C# Script, it is returning Null. It could be related to the issue? Anybody know I can point Unity(pythonnet) to the correct Python path?

PS: I installed all packages from the NugetForUnity asset within Unity store.
ie; Keras.Net (within Unity), Numpy.Bare.OSX and PythonRuntime were automatically added as dependencies.

**Comment by deepakkumar1984** [comment]
Can you please install standard Python instead of ANaconda

**Comment by cxbxmxcx** [comment]
I believe you need to set these environment variables.

PYTHONHOME = C:\Users\conda\envs\Visual-Studio-01
PYTHONPATH = C:\Users\conda\envs\Visual-Studio-01

PYTHONHOME and PYTHONPATH should be set to interpreter path, aka python.exe

**Comment by myshiop** [comment]
Hi, I can't installed these packages, I don't know why. How do you installed these packages? Just click  the "install" without other settings? ><

**Comment by krishnanpc** [comment]
@deepakkumar1984 , thanks for your reply, will try that and let you know.

**Comment by krishnanpc** [comment]
@myshiop , just install using packages in Unity.

**Comment by myshiop** [comment]
@krishnanpc Thank you very much. I click "install", but I always failed. I don't know why, maybe it is because of my internet >_<

**Comment by krishnanpc** [comment]
I think you can install it via Nuget. but I havent tried it.
