### ISSUE TITLE
[Python] ImportError: DLL load failed 

### ISSUE THREAD

**Issue by Yanggum** [SciSharp/Keras.NET#11]
I run sample project, but I have a found error.

Python.Runtime.PythonException: 'ImportError : DLL load failed : cannot found procedure

Sequential.cs

```
public Sequential()
        {
            __self__ = Instance.keras.models.Sequential();
......
```

please help.

**Comment by deepakkumar1984** [comment]
Could you please check if Python 3.6 is installed? Are you using Virtual environment? What version of keras in installed? Are you using nuget package or direct project?

**Comment by Yanggum** [comment]
yes, and not virtual environment. and python keras is worked.

**Comment by deepakkumar1984** [comment]
Can you check the numpy version, if it 3.6.1.6, can you downgrade to 3.6.1.1 and test it?

**Comment by deepakkumar1984** [comment]
Are you able to check the issue with Numpy 3.6.1.1

**Comment by deepakkumar1984** [comment]
Please reopen if still having issues

**Comment by StijnVA** [comment]
I am having a similar issue. I have installed python 3.6.8 (and 3.7) but as soon as I hit  new Keras.Models.Model I got an error saying'Unable to load DLL 'python36' 

![image](https://user-images.githubusercontent.com/5576173/62951640-94536100-bdea-11e9-9aea-8aa8adb41eef.png)
