### ISSUE TITLE
Python.Runtime.PythonException: AttributeError : 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by xu998** [SciSharp/Keras.NET#113]
When I debug or release, no problem. But when I started .exe directly,it was wrong。
===========
Python.Runtime.PythonException: AttributeError : 'NoneType' object has no attribute 'write'
    Python.Runtime.Runtime.CheckExceptionOccurred()
    Python.Runtime.PythonEngine.ImportModule(String name)
    Keras.Keras.InstallAndImport(String module)
    Keras.Keras.<>c.<.cctor>b__27_0()
    System.Lazy`1.CreateValue()
    System.Lazy`1.LazyInitValue()
    Keras.Models.BaseModel.LoadModel(String filepath, Dictionary`2 custom_objects, Boolean compile)
    WindowsFormsApp2.Form1.Form1_Load(Object sender, EventArgs e) C:\Users\vokxc\source\repos\WindowsFormsApp2\WindowsFormsApp2\Form1.cs:line 33
    System.Windows.Forms.Form.OnLoad(EventArgs e)
    System.Windows.Forms.Form.OnCreateControl()
    System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
    System.Windows.Forms.Control.CreateControl()
    System.Windows.Forms.Control.WmShowWindow(Message& m)
    System.Windows.Forms.Control.WndProc(Message& m)
    System.Windows.Forms.Form.WmShowWindow(Message& m)
    System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
=============
CODE:

        private void Form1_Load(object sender, EventArgs e)
        {  
        
             BaseModel  model2 = BaseModel.LoadModel(System.Environment.CurrentDirectory + "\\" + "cnn.model");

        }

**Comment by xu998** [comment]
python  3.7.5   x64

**Comment by deepakkumar1984** [comment]
Here is the solution: https://github.com/SciSharp/Keras.NET/issues/86

Try with disabling console
Keras.Keras.DisablePySysConsoleLog = true; at start,or onload .
