### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by Rotyak85** [SciSharp/Keras.NET#12]
Hi,

compliment for this cool project!

i'm trying to run the _MNIST CNN Example_ but i get this exception:

System.MissingMethodException:
Impossibile trovare il metodo 'Void Numpy.NDarray..ctor(Python.Runtime.PyObject)'
(not found method translated)

stacktrace:

`in Keras.Helper.TupleSolver.GetNdListFromTuple(PyObject obj, List`1& result)
`in Keras.Helper.TupleSolver.TupleToList(PyObject obj)`
`in System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)`
`in Keras.Datasets.MNIST.LoadData(String path)`
`in KerasTest.Program.Main(String[] args)`

this is my conda environment's packages list:

_tflow_select
absl-py
astor
blas
ca-certificates
certifi
chardet
cudatoolkit
cudnn
gast
google-pasta
grpcio
h5py
hdf5
icc_rt
idna
intel-openmp
joblib
keras-applications
keras-base
keras-gpu
keras-preprocessing
keras2onnx
libprotobuf
markdown
mkl
mkl-service
mkl_fft
mkl_random
mock
numpy
numpy-base
onnx
onnxconverter-common
onnxmltools
openssl
pip
protobuf
pyreadline
python
pyyaml
requests
scikit-learn
scipy
setuptools
six
skl2onnx
sqlite
tensorboard
tensorflow
tensorflow-estimator
tensorflow-gpu
tensorflow-hub
tensorflowjs
termcolor
typing
typing-extensions
urllib3
vc
vs2015_runtime
werkzeug
wheel
wincertstore
wrapt
yaml
zlib

i run all into an envs with python 3.6, i've installed also tensorflowjs and onnxmltools (these by pip), and the initial warnings of their lack are gone.

i have no idea, any suggestion?

**Comment by deepakkumar1984** [comment]
Could you please share the project?

**Comment by Rotyak85** [comment]
The problem seems to have been the versions of packages, i re-installed the environment without keras-gpu package (not in conda this time), and i downgraded Python.Runtime.NET from 3.6.1 to 3.6.0, and then re-upadated, now the error is changed: 

"RuntimeError : tf.placeholder() is not compatible with eager execution." I saw the relative issue and i'm working to understand which is the problem.

i have two warnings during the execution:

W0730 10:36:26.488378  2664 deprecation_wrapper.py:119] From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0730 10:36:26.509323  2664 deprecation_wrapper.py:119] From C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

maybe they lead indirectly to the problem

[KerasTest.zip](https://github.com/SciSharp/Keras.NET/files/3445924/KerasTest.zip)

**Comment by Rotyak85** [comment]
These rows resolve  all:

var backend = Backend.Instance.keras.backend.tf;
backend.disable_eager_execution();

now only the gpu execution remains

**Comment by Rotyak85** [comment]
All resolved, i re-installed tensorflow-gpu: i want post my configuration, maybe it can help other:

pip.exe --list:
absl-py              0.7.1
astor                0.8.0
certifi              2019.6.16
chardet              3.0.4
cycler               0.10.0
gast                 0.2.2
google-pasta         0.1.7
grpcio               1.22.0
h5py                 2.9.0
idna                 2.8
joblib               0.13.2
Keras                2.2.4
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
keras2onnx           1.5.1
kiwisolver           1.1.0
Markdown             3.1.1
matplotlib           3.1.1
numpy                1.17.0
onnx                 1.5.0
onnxconverter-common 1.5.2
onnxmltools          1.5.0
pandas               0.25.0
pip                  19.2.1
protobuf             3.9.0
pydub                0.23.1
pyparsing            2.4.1.1
python-dateutil      2.8.0
pytz                 2019.1
PyYAML               5.1.1
requests             2.22.0
scikit-learn         0.21.2
scipy                1.3.0
setuptools           41.0.1
six                  1.12.0
skl2onnx             1.5.0
sklearn              0.0
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
tensorflow-gpu       1.14.0
tensorflow-hub       0.5.0
tensorflowjs         1.2.3
termcolor            1.1.0
typing               3.7.4
typing-extensions    3.7.4
urllib3              1.25.3
Werkzeug             0.15.5
wheel                0.33.4
wrapt                1.11.2

python version: 3.6.5 final

vs2019 nuget package:
![image](https://user-images.githubusercontent.com/8393340/62158518-e8047b80-b30f-11e9-91c2-598add4aed1e.png)
