### ISSUE TITLE
construct fail to construct after dispose() call

### ISSUE THREAD

**Issue by NaJongHeon** [SciSharp/Keras.NET#123]
Dear Keras .NET team

I found that Keras.Layers.Input  construct fail to construct after dispose() call.

ex) 
Input Input_tensor = new Input(new Keras.Shape(img_rows, img_cols, img_ch), dtype: "float32", name: "input");
Input_tensor.dispose();
Input Input_tensor = new Input(new Keras.Shape(img_rows, img_cols, img_ch), dtype: "float32", name: "input"); <= Exception occurred

Thanks
![image](https://user-images.githubusercontent.com/24406907/82975868-93f22280-a018-11ea-96b5-735a44621c8f.png)

**Comment by MarceloManteigass** [comment]
Hello all, I'm having a similar issue. Any update on this?
Many thanks,
Marcelo Manteigas

**Comment by NaJongHeon** [comment]
I think it occurred a exception after we run it through not static class object.
