### ISSUE TITLE
Keras Callback

### ISSUE THREAD

**Issue by delphixx** [SciSharp/Keras.NET#13]
Hi! 
Your project is very useful and I appreciate your contribution! I started with the example and  wanted to customize the Keras Callback mechanism to show the model.fit progress to the user. 

But I don't really know how to do it:
Declaring a new class
`private class KerasCallback : Keras.Callbacks.Callback{}`

Creating the object:
`KerasCallback x1 = new KerasCallback();
` 

And then send to fit:
`model.Fit(x, y, batch_size: 2, epochs: 1000, verbose: 1, callbacks: new Callback[] { x1 });`

And all I get is: 
Python.Runtime.PythonException: AttributeError - Callback object has no attribute Invoke.

It seems as I missed to declare a method or property to the class. Any ideas? 
Maybe you could extend one of the examples with the solution.

Thanks in advance!

**Comment by deepakkumar1984** [comment]
Thanks for the appreciation. Are you trying to build a custom callback? Could you please let me know what the callback function will do so that I can try to implement it or provide you solution?

**Comment by delphixx** [comment]
Yes I try to build a custom callback! I want to get the step, batch, training and validation score value - let’s say in a Console.WriteLine output. How can I do it?

**Comment by delphixx** [comment]
Any Ideas on how to make a delegate for example on_batch_end or on_train_begin?

**Comment by deepakkumar1984** [comment]
Didn't get much time last few weeks, will try to come up with an example for your requirement by this week

**Comment by deepakkumar1984** [comment]
I am able to come up with a solution to implement custom callback. Since the library is a wrapper for the Keras python, the custom callback need to be a python code only. Here it the example: https://github.com/SciSharp/Keras.NET/blob/master/Examples/BasicSamples/ImplementCallback.cs

Steps1: Create a python file with your callback implementaion.Took an example from keras documentation itself:

```
import keras

class LossHistory(keras.callbacks.Callback):
    def on_train_begin(self, logs={}):
        self.losses = []

    def on_batch_end(self, batch, logs={}):
        self.losses.append(logs.get('loss'))
        print("Custom Callback: " + str(logs.get('loss')))

```

Step2: In your .NET project use the Calback.Custom method which can take the file or code to give you instance of callback object. Pass the callback instance to fit method. You can access the custom properties defined in the python implementation:

```
var lossHistory = Callback.Custom("LossHistory", "LossHistory.py");

//Compile and train
model.Compile(optimizer: new Adam(), loss: "binary_crossentropy", metrics: new string[] { "accuracy" });
var history = model.Fit(x, y, batch_size: 2, epochs: 10, verbose: 1, callbacks: new Callback[] { lossHistory });

var customLosses = lossHistory.Get<double[]>("losses");
```

**Comment by deepakkumar1984** [comment]
![image](https://user-images.githubusercontent.com/6328361/63069652-eb764480-bf56-11e9-80e7-cc759b05e8ab.png)

See the result the custom callback in invoked by printing the message.

**Comment by deepakkumar1984** [comment]
Please reopen if still need help

**Comment by delphixx** [comment]
Thanks for the example! This helps me a lot!

Is there a way to create a delegate method that fires on every training step in C# ?

**Comment by deepakkumar1984** [comment]
Since most of the core functionality is written in python and Keras.NET invoke those functions, so its not possible to hook .NET delegates within Python.

**Comment by delphixx** [comment]
Ok! Thank you!
