### ISSUE TITLE
Fit HistoryLog bug

### ISSUE THREAD

**Issue by jacosoft** [SciSharp/Keras.NET#14]
Hi 
Thanks for a great project!
I believe I found a bug and would like to propose a solution?
In Keras/Callbacks.cs on line 110, the HistoryLogs property is returned as follows:
public double[] HistoryLogs
{
     get
     {
            return ((PyObject)__self__.history).As<double[]>();
     }
}

But in the original Keras python source code, the history property is a dictionary, not an array.
Wouldn't something like the below be more correct?
return ((PyObject)__self__.history).As<Dictionary<string,double[]>>();

Thanks again
Jakes

**Comment by deepakkumar1984** [comment]
Thanks for the appreciation, I will try to fix it in next 2 days and update the nuget.

**Comment by deepakkumar1984** [comment]
Fixed with the latest version. Please update nuget

**Comment by deepakkumar1984** [comment]
Now history log will give Dictionary<string, double[]>

**Comment by jacosoft** [comment]
Awesome, thank you so much!

**Comment by jacosoft** [comment]
I tested and it works perfectly now, thanks!
