### ISSUE TITLE
System.IO.FileNotFoundException occuring in mscorlib.dll?

### ISSUE THREAD

**Issue by DoraAHsu** [SciSharp/Keras.NET#145]
When I try to compile some Keras sample, I got some error.

One problem is System.IO.FileNotFoundException occurring in mscorlib.dll.
The second problem is  Microsoft.CSharp.RuntimeBinder.RuntimeBinderException occurring in Microsoft.CSharp.dll

Is it possible to fixed?

**Comment by deepakkumar1984** [comment]
Should be fixed with latest versions
