### ISSUE TITLE
Error Python.Runtime.PythonException: "NameError : name 'tf' is not defined"

### ISSUE THREAD

**Issue by alexgurenko** [SciSharp/Keras.NET#147]
Hello!

I am trying to load a model generated by Keras-Applications == 1.0.8. I am using Keras == 2.4.3 and the latest Keras.Net.

When I load the h5 model I see an error Python.Runtime.PythonException: "ValueError : Unknown layer: BatchNorm". I renamed this layer to BatchNormalization in the JSON file. But when i load json i get the error "NameError: name 'tf' is not defined"

How to fix it? Maybe exist way for convertation h5 model for new version of Keras?

**Comment by DoraAHsu** [comment]
I think that you can try to generate the new model by version 2.4.3 and load the h5 model again.

**Comment by deepakkumar1984** [comment]
NBow its using tensorflow keras so please install tensorflow  only
