### ISSUE TITLE
run  keras.net based built exe on computer that does not have python installed?

### ISSUE THREAD

**Issue by sam0458** [SciSharp/Keras.NET#148]
I built the keras.net app and ran it  as exe file without problem on the computer with installed python3.7. Then I copied the release directory to another computer and added python.dll and python37.dll. That computer did not have python 3.7 installed. When I ran exe file I got
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

I am wondering how to build keras.net based C# exe or embedded dll application and run  on computer that does not have python installed?

**Comment by DoraAHsu** [comment]
Me too.

**Comment by sam0458** [comment]
Eventually I figure out. See description

https://docs.microsoft.com/en-us/dotnet/core/deploying/

I have build from VS as Debug x64 and then ran:
dotnet publish -r win-x64 --self-contained false

The content of publish directory was my app in other computer.

The same works for tensorflow.net samples.

**Comment by sam0458** [comment]
Correction:
dotnet publish -r win-x64 --self-contained true

I did not try with false yet.

**Comment by sam0458** [comment]
I was wrong. The publish works only for tensorflow.net samples but not for keras.net. Still the same error.

**Comment by Nodice** [comment]
Keras requires Tensorflow, which requires Python (Mostly). It uses Python.Runtime as it's interface, so you can't get around the Python requirement with the current version.

There is no pure binary version of Keras that I know of.

There is the newer Tensorflow.NET which does not require Python but it's much more difficult than Keras for beginners, especially now that Google has converted all of their training to Keras. I don't know if Google plans on developing a pure c++ API for Keras. This would be a requirement to have Keras operate outside of Python.
