### ISSUE TITLE
TrainOnBatch(), Predict(), .. need an overload for multiple inputs

### ISSUE THREAD

**Issue by kroll-software** [SciSharp/Keras.NET#151]
https://keras.io/api/models/model_training_apis/#trainonbatch-method

x: Input data. It could be:
A Numpy array (or array-like), _or a list of arrays_ (in case the model has multiple inputs).

public double[] TrainOnBatch(NDarray[] x, ..

Cheers,

**Comment by deepakkumar1984** [comment]
Added overload for TrainOnBatch, TestOnBatch and PredictOnBatch to allow taking NDArray list.
