### ISSUE TITLE
How to load onnx model in Keras.net

### ISSUE THREAD

**Issue by Aleksey1555** [SciSharp/Keras.NET#152]
Hello
on this [page](https://github.com/onnx/models#object_detection), there are many models in onnx format.
I tried  [Yolo v3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3)
I convert onnx to tensorflow pb file like [this](https://github.com/onnx/onnx-tensorflow).
command:
`onnx-tf convert -i yolov3.onnx -o saved_model.pb`
and this command finish successfully!
And then in C# code i try load model like this:
` BaseModel bm = Sequential.LoadModel("folder with saved_model.pb file")`

But i get error:
**String field 'tensorflow.MetaGraphDef.MetaInfoDef.meta_graph_version' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.**

Please help!
What i do wrong?

**Comment by deepakkumar1984** [comment]
I have updated the code to use tensorflow.keras  which will be maintained. Try with the latest keras.net to see if that fixed the issue.
