### ISSUE TITLE
Use SciSharp Keras.NET for not sequential layers 

### ISSUE THREAD

**Issue by MariaNazarenko** [SciSharp/Keras.NET#153]
I am using a TensorFlow with a Keras backend  based neural network for image segmentation. Model of my convolutional network has the U-Net artitecture. I wrote a model in python and trained it. I want to use it from C#. I seek to use the SciSharp Keras.NET library, but examples are only for a model with sequential layers. Can I use library SciSharp Keras.NET if my layers is not sequential?

**Comment by deepakkumar1984** [comment]
Yes you can, if not can you raise issue with an example.
