### ISSUE TITLE
Predict using Yolo v3 returns inaccessible results

### ISSUE THREAD

**Issue by Aleksey1555** [SciSharp/Keras.NET#154]
Hello.
I try to predict with yolo v3 model. 
Code below:
```
using K = Keras.Backend;
...
K.DisableEager();
BaseModel model = Sequential.LoadModel("path to my h5 file");
model.Compile(loss: "categorical_crossentropy",
              optimizer: new Adadelta(), metrics: new string[] { "accuracy" });
NDarray res=model.Predict(img);
```
This code work's, but in debuger (Visual Stuido 2019 CE), i see this:

![picture](https://user-images.githubusercontent.com/32514002/89945835-a8fb4c80-dc2a-11ea-9ea5-4d34452e4154.jpg)

As you can see, i can't access to any property or field (((
And when I try to access through the indexer ( like `res[0]`), it returns me error: **TypeError : list indices must be integers or slices, not tuple**
I also tryed this:
`NDarray res2=np.array(res)`
but i get error: **ValueError : could not broadcast input array from shape (13,13,255) into shape (1)**

Also, i tryed do the same on python and keras (not Keras.Net) and it worked. 
code below:
```
from tensorflow import keras
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array

model=keras.models.load_model("\\yolov3.h5")
img=load_img("zebra.jpg",target_size=(416,416))
arr=img_to_array(img)
arr=arr.astype('float32')
arr/=255.0
arr2=arr.reshape(1,416,416,3)
res=model.predict(arr2)
print(res[0])
```

print(res[0]) - successfully show arrays

**Comment by Aleksey1555** [comment]
please help!

**Comment by Nodice** [comment]
I just read a bit of code that may help you.

var predictions = model.DecodePredictions(preds, top: 2);

Found in: https://github.com/SciSharp/Keras.NET/blob/master/Examples/ImageExamples/ImageRecognition.cs
