### ISSUE TITLE
Convert array to image

### ISSUE THREAD

**Issue by Pelectrome** [SciSharp/Keras.NET#155]
i'm trying to convert array to image from dataset
i did this : var image = ImageUtil.ArrayToImg(x_train[0]);
but this object give me now way to get the data of the image i want to convert it in bitmap in the end 
i hope someone can help.

**Comment by Nodice** [comment]
I did not test this idea, but ArrayToImg returns a Pil Image

https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/array_to_img

You should be able to call image.save("Filename")
If not you can look into how to save a PIL Image in Python and then mimic it.

You can also get your x_train[0] to a byte array and then do this:

byte[] imageBytes = new byte[100];
MemoryStream ms = new MemoryStream(imageBytes);
Bitmap BM = new Bitmap(ms);
BM.save("PathToImageSave");
