### ISSUE TITLE
Tokenizer method returning error

### ISSUE THREAD

**Issue by danielriddell21** [SciSharp/Keras.NET#159]
I use the FitOnTexts() method and it throws out the error

Python.Runtime.PythonException: 'TypeError : fit_on_texts() missing 1 required positional argument: 'texts''

I am passing to the method an array of strings

**Comment by Garretenion** [comment]
Are there any news here? Struggeling with the same problem. 

Edit: the doc shows a 404 at this point. I really appreciate your help here! Thank you so much for your great work!

**Comment by Garretenion** [comment]
Any news here? ;/

**Comment by arguib** [comment]
Still having the same problem as of now (I'm trying to do "One-hot encoding of words or characters" by F. Chollet in C#)

EDIT: Nevermind, check this issue, they found a solution.
https://github.com/SciSharp/Keras.NET/issues/25#issuecomment-763988431
