### ISSUE TITLE
How to use Bitmap in Keras.NET

### ISSUE THREAD

**Issue by OwenAsi** [SciSharp/Keras.NET#168]
Now I can use ImageUtil.LoadImg to load image, but I want to use Bitmap to predict.  I can't find how to convert Bitmap to NDarray.

**Comment by MiroslavKabat** [comment]
I am using NumSharp NDArray converted to Numpy NDarray. It works fine and pretty fast.

**Comment by OwenAsi** [comment]
@MiroslavKabat Do you mean I need to convert Bitmap to NumSharp NDArray, then convert to Numpy NDarray? Could you please elaborate on it? Thanks.

**Comment by MiroslavKabat** [comment]
This is how I do it exactly.
'img' is 'System.Drawing.Image'

// To NumSharp array
var nsArr = img.ToNDArray(false, true, true);

// To .NET array
var fArr = nsArr.ToArray<byte>().Select(x => (float)x).ToArray();

// To numpy array
NDarray npArr = np.array(fArr, np.float32).reshape(h, w, 3);

**Comment by OwenAsi** [comment]
@MiroslavKabat 
// The following occurs error,
var fArr = nsArr.ToArray().Select(x => (float)x).ToArray();
// So I modify it as below, and compile it successfully 
var fArr = nsArr.ToArray<byte>().Select(x => (float)x).ToArray();

But it takes about 50ms on i7-3770 with image size(512,512,1).
Is there anything wrong with the modification?

**Comment by MiroslavKabat** [comment]
I can't know what is your network architecture or project itself about. 
You can use same pattern with different types int8 / uint8 / whatever you want ...

// for image 2560 x 1920 x 3 (5 Mpx rgb) (19x larger like yours)
// To NumSharp array (86 ms)
var nsArr = img.ToNDArray(false, true, true);

// To .NET array (7 ms)
var fArr = nsArr.ToByteArray();

// To numpy array (26 ms)
var nparr = Numpy.np.array(fArr, Numpy.np.int8, true);

This is much faster. But you needs to build and train your network ready for that format.
Anyway for me is pretty handy and more comfortable use float32 in range 0÷1 despite of loading time and memory consumption. 

(Intel Core i9 10980XE)

**Comment by OwenAsi** [comment]
@MiroslavKabat 
Using the "ToByteArray" method is faster than before, but the returned array size is not the same as the image size. It seems the "BytesLength" of NDArray to decide the returned array size.

**Comment by MiroslavKabat** [comment]
It returns bgra or something like that... Slice it or w/e

**Comment by OwenAsi** [comment]
@MiroslavKabat 
I will try. I really appreciate you.
