### ISSUE TITLE
model.predict function is stopped with my exe file.

### ISSUE THREAD

**Issue by jhbum01** [SciSharp/Keras.NET#169]
I loaded h5 files and predicted in visual studio 2019.
At that time it worked OK.
But In EXE file of  my bin/release. predict function was stopped and I could not get return value when predict my new data.

Please give me your advise.

Thank you

**Comment by MovEaxEax** [comment]
Well, there are too many reasons for why your assembly crashed. Share your full code, or at least the passage where you do the prediction.
