### ISSUE TITLE
dll not found exception in Ubuntu

### ISSUE THREAD

**Issue by shv07** [SciSharp/Keras.NET#173]
Hi,

I am trying to deploy a self contained dotnet core app which uses keras.NET in Ubuntu 16. It shows an error of dll not found exception. I used to get same error in windows but was solved by making python 3.7 the default python there. But in ubuntu doing that also does not help.

![image](https://user-images.githubusercontent.com/25014324/100224594-09489c80-2f43-11eb-9bf1-e60e05f93b8f.png)

**Comment by erichiller** [comment]
Most likely you're using the Windows package `Keras.Net` when you need the Linux package [`Keras.Net.Mono`](https://www.nuget.org/packages/Keras.NET.Mono/)
