### ISSUE TITLE
Installing this software

### ISSUE THREAD

**Issue by nilscognite** [SciSharp/Keras.NET#174]
It is hard to understand the dependencies. In the readme it is stated "Install keras, numpy and one of the backend (Tensorflow/CNTK/Theano). Please see on how to configure: https://keras.io/backend/". ?????  It cause me a lot of frustration, I did not found any relevant information, at least a direct link to a download with the correct versions. It is just to hard to make it work. I think this code and the examples are excellent, but for me it is not possible to use or run. And at last, if I send this software to other, do they have to download all this thing themselves? 

Note: I  have been a C# developer in 15+ years, with limited python experience. Isn't the point with this code that you shouldn't know a lot about python?

**Comment by Oceania2018** [comment]
Everything you need to do is downloading [example project](https://github.com/SciSharp/SciSharp-Stack-Examples) and hit run.

**Comment by nhirschey** [comment]
My impression was similar to @nilscognite. I think the installation instructions could use more clarity (hence https://github.com/SciSharp/Keras.NET/pull/178). 

Thank you for the tip on building that SciSharp example project. I did this and it does seem to build and run without any dependencies.
