### ISSUE TITLE
Merge concatenation

### ISSUE THREAD

**Issue by individ2016** [SciSharp/Keras.NET#18]
Can i somehow do concatenate layers? 
I want to get multichannel CNN Model, but didnt found any able to do it.. 
Merge layer didnt concat my layers :(

And yes!!))) Thank you for this package!!! Its awesome!)

**Comment by individ2016** [comment]
And yes!!))) Thank you for this package!!! Its awesome!)

**Comment by deepakkumar1984** [comment]
Can you send me a sample code with the expected result, will be easy for me to fix it and test it out?

**Comment by individ2016** [comment]
I wanted to realize network like in description after header "Shared Input Layer" on page https://machinelearningmastery.com/keras-functional-api-deep-learning/

I do not shure that data prepared correctly at all, but model described in CreateModel method in file 'MultiCNNInput.cs'

Thank you! :)

[test.zip](https://github.com/SciSharp/Keras.NET/files/3488591/test.zip)

**Comment by HaileyStorm** [comment]
Following.

**Comment by deepakkumar1984** [comment]
Resolved with latest checkin
