### ISSUE TITLE
Difference between Tensorflow.NET.keras and Keras.NET?

### ISSUE THREAD

**Issue by HyeokSuLee** [SciSharp/Keras.NET#185]
is there any differ? 
I 've tried to use Tensorfow.NET 0.23.1 with unity.
But there is so much not implemented exception.
So i raised to 0.32.0.
And suddenly i've found this Keras.NET. So, I confusing cause Scisharp team made Tensorflow.NET and Keras.NET.
However Tensorflow.NET includes Tensorflow.keras. Idon't know which one is better, so now I'm using both at same time.
But there are many things overlaping each other. Can someone tell differ and pros, cons of these?

**Comment by Oceania2018** [comment]
The main difference is:
TensorFlow.NET and TensorFlow.Keras don't rely on python environment.
Keras.NET relies on python installation.
