### ISSUE TITLE
Does Keras.net inference slower than python keras?

### ISSUE THREAD

**Issue by PMC-AI** [SciSharp/Keras.NET#187]
I use same image size and CNN architecture running on cpu. But on my testing result, python keras inference speed is faster than Keras.net 3 times. Is this correct?

**Comment by fashrista** [comment]
I also have found keras.net to be even more than 3 times slower when running on the same GPU. Have you @PMC-AI found any solutions for this?

**Comment by PMC-AI** [comment]
@fashrista  Not yet. I given up Keras dot net.  Now I try tensorflow dot net.

**Comment by fashrista** [comment]
@PMC-AI is that one faster?

**Comment by PMC-AI** [comment]
The architecture of tensorflow dot net looks like faster than keras dot net. Currently I know tensorflow dot net it must be build from VS2019, or you will meet many problems. And tensorflow dot net has a lot of nuget packages that it makes your executable file very heavy. Um...but now I'm busy. I have not tried it.
