### ISSUE TITLE
Unable to load DLL 'python38' or one of its dependencies: The specified module could not be found

### ISSUE THREAD

**Issue by FatemehEsfahani** [SciSharp/Keras.NET#191]
Hi, I have tried to load my cnn model in C# visual studio. I have trained my model using keras in python. 
When I use the following command:
var loaded_model = Sequential.ModelFromJson(File.ReadAllText("C:/Users/xxx/Downloads/model1.json"));
I get an error that python dll files cannot be found. 
I have used anaconda for python installation and keras and tensorflow are installed in anaconda. I was wondering how I can make the python path available to my project?
Thank you for your help.

**Comment by erichiller** [comment]
~~I also have this issue, let me know what information I can provide to help.~~

Most likely you're using the Windows package `Keras.Net` when you need the Linux package [`Keras.Net.Mono`](https://www.nuget.org/packages/Keras.NET.Mono/)

(I was)

**Comment by FatemehEsfahani** [comment]
keras.net uses python. So, python should be installed on the computer. It seems that the installation with anaconda causes that error.
