### ISSUE TITLE
is there any setting like ```gpu_options.allow_growth=true``` in keras.net?

### ISSUE THREAD

**Issue by nothasson** [SciSharp/Keras.NET#192]

**Comment by fashrista** [comment]
Have you found a solution for this?
wold like to do this:
`phisical_devices = tf.config.experimental.list_physical_devices('GPU')
            print("Num of GPUs: ", len(phisical_devices))
            tf.config.experimental.set_memory_growth(phisical_devices[0], True)`

**Comment by nothasson** [comment]
> 

I take c# as the client and python as the server, and use post request to transfer the picture for calling the predict method

**Comment by nothasson** [comment]
> 

I take c# as the client and python as the server, and use post request to transfer the picture for calling the predict method
