### ISSUE TITLE
C# - Calling python function doesn't return

### ISSUE THREAD

**Issue by patmach** [SciSharp/Keras.NET#194]
I'm developing card game that is played by neural network. I'm using Keras.NET library and calling model.predict (model is instance of Sequential class). 

This is only part where python is called, when game is played:
```
 public override List<float> GetResult(List<float> input)
        {
            var NDArrayResult = model.Predict(new Numpy.NDarray<float>(input.ToArray()).reshape(1, inputCount, 1), verbose: 0);
            float[] result = NDArrayResult.GetData<float>();
            return result.ToList();
        }
```

I have 2 different startup project, one is ConsoleApp, where everything goes just fine. But if I play game in my Windows Forms app, first few (1,2,3,4,..) python calls are successful, but then it's just doesn't return from calling python function... Sometimes it stops in the ```Predict``` function, sometimes in ```reshape```.

**Does anyone know, where could be problem? Or how to solve the problem so that game can continue?**

I tried to call this part of code as a task and wait for period of time and then call the method again. It worked but occasionally caused the System.AccessViolationException...

**Comment by win7user10** [comment]
@patmach Do you solve this issue? I have the same problem, my model returns result only for the first call of Predict(), and other calls cause freeze

**Comment by GilmarCoop** [comment]
Were you able to solve this problem?
