### ISSUE TITLE
Adding a model as a Layer

### ISSUE THREAD

**Issue by arguib** [SciSharp/Keras.NET#195]
Can't I add a Keras.Applications.VGG.VGG19 model in a Keras.Models.Sequential model?

**Comment by nor0x** [comment]
i'm also looking for a solution to use something like this - which totally works in the python code

```
model1 = Sequential()
model2 = Sequential()
model2.add(model1)
```

Maybe this extension method helps you - it gets all the layers from a `BaseModel`


```
public static BaseLayer[] Layers(this BaseModel model)
{
    var lstLayers = new List<BaseLayer>();
    var layers = model.ToPython().GetAttr("layers");
    foreach (var layer in layers)
        lstLayers.Add(new BaseLayer(layer as PyObject));
    return lstLayers.ToArray();
}
```


**_UPDATE:_**

i just got it working with the following extension method

```
public static BaseModel Add(this BaseModel model, BaseModel otherModel)
{
    var py = model.ToPython();
    py = py.InvokeMethod("add", new PyObject[] { otherModel.ToPython() });
    return py.As<BaseModel>();
} 
```

**Comment by arguib** [comment]
Thanks for the short reply and your solution. Helps a lot.

I was actually trying to loop the different layers on my BaseModel model to add them to my Sequential but couldn't retrieve them through BaseModel methods...
