### ISSUE TITLE
Crash on Unity

### ISSUE THREAD

**Issue by akaimody123** [SciSharp/Keras.NET#199]
Hi, I managed to use Keras.NET in unity3d with windows 10, python3.8. However, it only allows me to run the editor for one time successfully, then it always crash on the second time. Could you please advise me on that? Thank you very much!

**Comment by MovEaxEax** [comment]
How you use it in Unity? Maybe share some code. 
Where does it crash? In editor or in game?

It's maybe because GPU usage. Watch your GPU performance in Taskmanager, or something else.
