### ISSUE TITLE
Keras issues

### ISSUE THREAD

**Issue by natank1** [SciSharp/Keras.NET#2]
When I try to run Keras.net I see two obstacles
1. Keras brings with numpy.bare  with no python.included so it alerts that there is no python,dll
2 If I use Numpy (which contains python.included)then Numpy and Numpy.bare conflict on some definitions.
What is the right way?

**Comment by henon** [comment]
The right way for Keras is to use it with Python installed locally. Because the dependencies of Keras are very big (Tensorflow GPU is huge) we decided not to include it in the nuget package. Thus, Numpy.Bare is required instead of Numpy because otherwise there would be a conflict between two different Python environments.

**Comment by natank1** [comment]
Thanks and what do I do with python.included that we have in numpy and not in numpy.bare

**Comment by henon** [comment]
Python.Included packages embedded Python and is able to install it on first execution, nothing else. You don't need it for Keras.NET.

Keras.NET should reference Numpy.Bare and Pythonnet_NetStandard

Numpy.Bare.dll references Pythonnet_NetStandard
(Numpy.dll references Python.Included which references Pythonnet_NetStandard) <--- not needed here

**Comment by natank1** [comment]
What is the best way to do one hot coding in numpy.bare?

**Comment by deepakkumar1984** [comment]
Can you try this code using Numpy, 

nb_classes = 6
targets = np.array([[2, 3, 4, 0]]).reshape(-1)
one_hot_targets = np.eye(nb_classes)[targets]

This is a Python reference, just need to rewrite in C#

**Comment by deepakkumar1984** [comment]
In keras there is a Util.ToCategorical function to one hot code the numpy array. Please use the reference of MNIST example: https://github.com/SciSharp/Keras.NET/blob/master/Examples/ImageExamples/MNIST_CNN.cs

**Comment by henon** [comment]
@natank1: please open a new issue for every question. the original question is answered so I am closing this

**Comment by natank1** [comment]
Thanks for your help
Actually (I write it for the other developers)
Both of your offers:

            int nb_classes = 3;
            NDarray targets = np.array( 1, 2, 0, 1, 0,0,1,2,1,2,0 );
            NDarray zz= np.eye(nb_classes);
            Console.WriteLine(zz[targets]);


As well as
            NDarray yy = np.load("your file");
            NDarray y_test = Util.ToCategorical(yy,  nb_classes  );
   works well.

The latter simply requires Keras

Natan
