### ISSUE TITLE
Can I use the repo to load StyleGan2 Keras pre-trained model to make predication?

### ISSUE THREAD

**Issue by zydjohnHotmail** [SciSharp/Keras.NET#224]
Hello:
I see there is one Keras implemention for StyleGan2 at this Github repo:
https://github.com/leoHeidel/stylegan2-keras
But the repo is written in Python, can I can never use Python based model for Windows 10, there is all kinds of bugs in Python software package chain. (Have to install countless Python packages.)
So, I want to know if I can use this repo to load some pre-trained Keras model and use the model to make an image from input image.
Or, if it is not possible directly, can I use this repo to train some dataset with StyleGan2 model and make predication after training is completed.
If possible, then please provide some general instructions.
Thanks

**Comment by CorentinPtrl** [comment]
Yes, u can load pre-trained model

**Comment by zydjohnHotmail** [comment]
Hello:
Can you show me some code to load one pre-trained model?
Thanks,

**Comment by CorentinPtrl** [comment]
For example this sample show how to create and load a h5 model
https://github.com/SciSharp/Keras.NET/blob/c1eecbd9235a2606d5b58c1b809e2e0fafa8c296/Examples/ImageExamples/Cifar10_CNN.cs#L107

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply. I will do some tesing.

**Comment by CorentinPtrl** [comment]
No problem
