### ISSUE TITLE
How to select specific GPU for Model Prediction?

### ISSUE THREAD

**Issue by thefillture** [SciSharp/Keras.NET#225]
Hi, I have a computer with 4 GPU installed , however , I would like to select only 1 specific GPU to do model prediction using keras.NET.
How can I go about doing this ?
Like example , using only GPU 2 to do model prediction , while the rest of the GPU can do other stuff.

**Comment by CorentinPtrl** [comment]
Hello, if you want to select ur gpu u need to set the environement variable "CUDA_VISIBLE_DEVICES" at 0, 1  or -1 for your cpu
(U need to set this variable before starting keras)

**Comment by thefillture** [comment]
Oh, Thanks for the reply. 
But does it hard code all my applications to be only using that GPU? 
Can I do it in such a way where different applications can use different GPU?

**Comment by CorentinPtrl** [comment]
No it will not apply for the other applications if you just set it in one app
