### ISSUE TITLE
Allowing custom parameters for "LoadModel"

### ISSUE THREAD

**Issue by iXyles** [SciSharp/Keras.NET#23]
After looking through the project and also testing loading custom objects I stumbled across issue of throwing exceptions when I try to load a model with custom objects (architecture): 
`var model = BaseModel.LoadModel(model_path);`

The solution for it in python is to pass a custom parameter example:
`model = models.load_model(model_path, backbone_name='resnet50')`

But currently the library is limited to not allowing any passing parameters in the BaseModel to support this sort of behavior. So the issue/request is basically to adding support for this through an optional parameter in LoadModel. 

Example of usage in Python (Mask RCNN with Keras) https://github.com/fizyr/keras-maskrcnn/blob/master/examples/ResNet50MaskRCNN.ipynb

**Comment by deepakkumar1984** [comment]
I will look into the example and try to implement. Thanks for pointing it out

**Comment by deepakkumar1984** [comment]
Please get the latest code and try it oout. Added additional arguments to take parameters.
Ex: Sequential.LoadModel("model.h5", new Dictionary<string, string>() { { "backbone_name", "resnet50" } });

**Comment by iXyles** [comment]
I think that is it! :)

I think I am just missing something else from the given example due to
`Python.Runtime.PythonException: 'TypeError : ('Keyword argument not understood:', 'freeze')'`
@ https://github.com/SciSharp/Keras.NET/blob/55bae30538ee68593a6e2b6e4c405696b7e19963/Keras/Models/BaseModel.cs#L356 

I believe this is because of custom loading of the model through keras_resnet, which I had completely missed yesterday - https://github.com/fizyr/keras-maskrcnn/blob/769092d7bec4c555751e3353d714900300d2cec8/keras_maskrcnn/models/resnet.py#L40

But thanks for adding in the support for this at least, I'll have to dig further to resolve my own issue :)

**Comment by Augis363** [comment]
Hey, 
If I have a  model with custom layer ("GaussianSampling") in it, is it possible to load the layer from the python object?
`codeToRedirectOutput = "from VAEModel.VAE import GaussianSampling";`
`PythonEngine.RunSimpleString(codeToRedirectOutput);`

`Dictionary<string, string> customObjects = new Dictionary<string, string>();`
`customObjects.Add("GaussianSampling", "GaussianSampling");`
`bool compile = false;`
`BaseModel model = BaseModel.LoadModel(this.ModelPath, customObjects,  compile); //this.customObjects,`
