### ISSUE TITLE
how can we do Multiple output network?

### ISSUE THREAD

**Issue by mshanak** [SciSharp/Keras.NET#237]
I would ask if Tensorflow.net support multiple output?

In python version we can configure the model to have multiple outputs layer. in the following example, the network will have two outputs (`outputs=[y1_output, y2_output]`)

```python
def build_model():
    # Define model layers.
    input_layer = Input(shape=(len(train .columns),))
    first_dense = Dense(units='128', activation='relu')(input_layer)
    # Y1 output will be fed from the first dense
    y1_output = Dense(units='1', name='price_output')(first_dense)

    second_dense = Dense(units='128', activation='relu')(first_dense)
    # Y2 output will be fed from the second dense
    y2_output = Dense(units='1', name='ptratio_output')(second_dense)

    # Define the model with the input layer and a list of output layers
    model = Model(inputs=input_layer, outputs=[y1_output, y2_output])

    return model

```

Can we have such functionality in the .NET version?

**Comment by DevNullx64** [comment]
You can buils this kind off model. It seem the "model.fit" method doesn't support more than one output tensor. I need this so I working on it. Prehaps there are juste a good Shaping yo use NDAray as mutliple output representation.

**Comment by DevNullx64** [comment]
I try to achive that too :)
