### ISSUE TITLE
Error loading Python DLL with PythonEngine

### ISSUE THREAD

**Issue by Thyssen1** [SciSharp/Keras.NET#247]
**Environment**
Pythonnet version: 3.0.1
Python version: 3.10.9
Operating System: Windows
.NET Runtime: 7.0.100

**Details**
I set the Runtime.PythonDLL to the path to the python DLL and then ran PythonEngine.Initialize() followed by the code from the MNIST example on the Keras.NET GitHub.
However, I get an MissingMethodException: Failed to load symbol Py_IncRef even though the DLL does exist.

See MNIST code on Github (scroll down): https://github.com/SciSharp/Keras.NET

**Comment by IgnacioRodriguez98** [comment]
I ignored if it is the same problem as mine, I had an error that said something like "Unable to find python38 DLL"

In my case, what I had to do was install python 3.8 and once installed I went to the folder where said version was installed and there was the DLL. Said DLL I only put it in the system32 folder and with that I solved it.

It should be noted that when installing python I checked the box that configured the path automatically and I also had python 3.11 installed before but with that it never worked, it was forced to ask for 3.8.
