### ISSUE TITLE
can we have the 'fit_on_texts' and 'texts_to_matrix' functions connected up from keras?

### ISSUE THREAD

**Issue by henon** [SciSharp/Keras.NET#25]
@ronedmeades asked this in Numpy.NET but I guess it is a Keras.NET issue:

> I've got to sleep but one other thing (I guess I do a lot with strings) but
> can we have the 'fit_on_texts' and 'texts_to_matrix' functions connected up
> from keras?  They are in keras.preprocessing.text import Tokenizer.  You
> create a new Tokenizer an then it exposes those methods.  Its useful when
> training models to deal with things like categorizing company names.
> Thanks for all the hard work, Ron

from

https://github.com/SciSharp/Numpy.NET/issues/14#issuecomment-521962444

**Comment by deepakkumar1984** [comment]
@henon: I will try to implement... Thanks

**Comment by deepakkumar1984** [comment]
Added the methods to Tokenizer

**Comment by danielriddell21** [comment]
I've tried to use these methods. But I get a 

Python.Runtime.PythonException: 'TypeError : fit_on_texts() missing 1 required positional argument: 'texts''

**Comment by Yashif** [comment]
I had the same issue,solved it by calling the init function after instantiate  the toknizer class
```  
          var tokenizer = new Tokenizer(num_words: 1000);
            tokenizer.Init();
            var texts = trainigDataArray;//from the method parameters
            tokenizer.FitOnTexts(texts:texts);

                // Encode training data sentences into sequences
            var train_sequences = tokenizer.TextsToSequences(texts);
```
     
I hope this helps
