### ISSUE TITLE
SystemDllNotfound exception : Unable to load python38 dll 

### ISSUE THREAD

**Issue by VinuthaRaghavendra** [SciSharp/Keras.NET#250]
1. Installed python version python3.8.0 added python path to system variable.
 - still getting unable to load python38.dll

Then copied python38.dll to the bin folder of the .net framework project. 
       Facing issue at the 
model = Kerala.models.model.load_model(.h5 file)
Model.predict(image)

error : attributeError: Nonetype object has no attribute write 
Python38/lib/site_packages/keras/src/utils/traceback_utils.py raise e.with_traceback from None from file keras/src/utils/io_utils.py line 79 print_msg sys.stdout.write(message) at python.runtime.pyobject.Invoke

**Comment by MarcoSal** [comment]
I have the same problem. can't find python38.dll. tried to change the enivromental system variable but nothing...

**Comment by MarcoSal** [comment]
I fixed it by installing python38 in C:\Program Files\Python38
then, before starting the KERAS routine, I entered this instruction

            ```
 string envPythonHome = @"C:\Program Files\Python38";
             string envPythonLib = envPythonHome + "\\Lib;" + envPythonHome + "\\Lib\\site-packages;" + envPythonHome + "\\DLLs";
             Environment.SetEnvironmentVariable("PYTHONHOME", envPythonHome, EnvironmentVariableTarget.Process);
             Environment.SetEnvironmentVariable("PATH", envPythonHome + ";" + Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.Machine), EnvironmentVariableTarget.Process);
             Environment.SetEnvironmentVariable("PYTHONPATH", envPythonLib, EnvironmentVariableTarget.Process);

             Python.Runtime.PythonEngine.PythonHome = envPythonHome;
             Python.Runtime.PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH");
```

it will probably give errors about libraries not installed at first. I have installed all the required libraries from time to time.
when done, the keras code works.

**Comment by LukePoga** [comment]
sick of this fucking trash hows anyone supposed to just run an install and have all this shit work? its lame. WHERE IS THE FUCKING WALKTHROUGH. Why waste our fucking time with random errors like can't find python38.dll and dont even give us a fucking walkthrough.
