### ISSUE TITLE
Keras.Models.LoadModel() raises exception

### ISSUE THREAD

**Issue by Hallupa** [SciSharp/Keras.NET#32]
I'm trying to load an h5 model using:

`BaseModel.LoadModel(@"C:\Models\model.h5");`

But I just get exception 'Python.Runtime.PythonException: 'TypeError : load_model() missing 1 required positional argument: 'filepath'''

I tested loading the model in Python using 
`loadedModel = keras.models.load_model("C:\Models\model.h5")`
which worked fine - so the issue is just in the c# version

**Comment by Hallupa** [comment]
I've downloaded the Keras.Net source code and have been investigating the issue further. I've found a possible fix for this and have created a unit test to reproduce.

I tried creating a branch to share the changes but get a permissions error - @deepakkumar1984  would it be possible to be granted access to creating a branch and pull request so I can share the changes?

**Comment by Oceania2018** [comment]
You can fork then PR.

**Comment by Hallupa** [comment]
Thanks Oceania2018, I've now done that

**Comment by deepakkumar1984** [comment]
> Thanks Oceania2018, I've now done that

Just checking if this issue is resolved now?

**Comment by Hallupa** [comment]
The code change fixes this issue, so this is resolved

**Comment by deepakkumar1984** [comment]
Thanks for your support
