### ISSUE TITLE
LearningRateSceduler Example

### ISSUE THREAD

**Issue by HaileyStorm** [SciSharp/Keras.NET#37]
How do we use the LearningRateScheduler?

I have code like such:

model.FitGenerator(t, steps, epochs, verbose: 0, callbacks: new Keras.Callbacks.Callback[] { new Keras.Callbacks.LearningRateScheduler(new Func<int, float>((e) => lrsched(e))) });

with lrsched defined as such:

 internal static float lrsched(int epoch) {
            float lr = (float)(0.0025f * Math.Exp(-0.017f * epoch));
            Console.WriteLine("Epoch: " + epoch.ToString() + ", new LR: " + lr.ToString());
            return lr;
        }

But, I get System.NotImplementedException: 'Type is not yet supported: Func`2. Add it to 'ToPythonConversions''. The comments in the source code for LearningRateScheduler say the object parameter should be a function ...

Any help you can provide, or an example?

Thank you!

**Comment by deepakkumar1984** [comment]
since this is a wrapper over python keras we need to pass Python function. I will find some example for you.

**Comment by HaileyStorm** [comment]
I got it sorted. After creating a shortcut to a subfolder in my project
directory inside my python Lib directory (C:\Program Files\Python36\Lib),
this code worked:

PyObject m;
            using (Py.GIL())
            {
                PyObject po = Py.Import("chainner_python.Callbacks");
                m = po.GetAttr("lr_schedule");
            }

            model.FitGenerator(t, steps, epochs, verbose: 0, callbacks: new
Keras.Callbacks.Callback[] { new Keras.Callbacks.LearningRateScheduler(m)});

**Comment by HaileyStorm** [comment]
I'm not sure why I had to symlink though honestly. Curious if you know a
solution that. Thanks!

**Comment by deepakkumar1984** [comment]
Not sure about python setup, it's hard to find any common setup, May be this question is for python community

**Comment by deepakkumar1984** [comment]
Do you still need help with this issue?

**Comment by HaileyStorm** [comment]
No I'm good on this issue now. Thank you.
