### ISSUE TITLE
TestOnBatch actually calls train_on_batch

### ISSUE THREAD

**Issue by IvoTops** [SciSharp/Keras.NET#39]
This routine in BaseModel.cs

public double[] TestOnBatch(NDarray x, NDarray y, NDarray sample_weight = null)

does

return InvokeMethod("train_on_batch", args)?.As<double[]>(); ; ;

**Comment by deepakkumar1984** [comment]
Ok.. I need to update the code for this. Will do that

**Comment by deepakkumar1984** [comment]
Fixed with latest code and nuget
