### ISSUE TITLE
Memory eaten up by unfreed python stuff

### ISSUE THREAD

**Issue by IvoTops** [SciSharp/Keras.NET#40]
Whenever I train a model from C# with a lot of TrainOnBatch calls my memory balloons out. Profiling said it was unmanaged memory that kees growing. I fixed it by doing a Dispose on every python object after usage (like the numpy arrays I pass to the routine). Not sure why the python runtime  does not seem to dispose all of it after it goes out of scope. 

Stuff like this in keras.net also seems to lose memory;

 return InvokeMethod("train_on_batch", args)?.As<double[]>(); ;

My fix was to put it into a var. That converted to the double[] and the var should then be disposed. Code looks below. Prettier and better ways might exist ;-)

var pyresult= InvokeMethod("train_on_batch", args);
var  dotnetresult=pyresult?.As<double[]>(); 
pyresult?.Dispose();
return dotnetresult;

**Comment by henon** [comment]
I ll see to it that out of scope pythonnet objects are disposed. Thanks for
reporting this!

Ivo Tops <notifications@github.com> schrieb am Mi., 25. Sep. 2019, 14:20:

**Comment by deepakkumar1984** [comment]
Implemented the change as suggested
