### ISSUE TITLE
Flatten() Error : __init__() takes 1 positional argument but 2 were given'

### ISSUE THREAD

**Issue by User2587** [SciSharp/Keras.NET#48]
I have installed the latest version keras 3.6.1.11 and I'm getting the below error
Python.Runtime.PythonException: 'TypeError : __init__() takes 1 positional argument but 2 were given'

This error occurred at model.Add(new Flatten());

**Comment by deepakkumar1984** [comment]
Are you able to execute the following example which is using flatten: https://github.com/SciSharp/Keras.NET/blob/master/Examples/BasicSamples/MNIST_CNN.cs

**Comment by User2587** [comment]
I'm getting same error for  MNIST_CNN.cs.
Additionally I got one more error popped up for 
           for   y_train = Util.ToCategorical(y_train, num_classes);
The error mentions
'TypeError : to_categorical() got an unexpected keyword argument 'dtype''

**Comment by deepakkumar1984** [comment]
It works for me. What version of keras and tensorflow you have?

**Comment by User2587** [comment]
keras 2.1.5 and tensorflow 1.6.0. I will check and let you know.

**Comment by deepakkumar1984** [comment]
Can you upgrade to latest keras which is 2.3.0.

Also upgrade the tensorflow to latest 2.0

**Comment by User2587** [comment]
I'm unable to reproduce this error, now it shows
 Exception thrown: 'Python.Runtime.PythonException' in Python.Runtime.dll

I'm afraid that latest keras may not work; last week I tried in python environment... its not working. 
Could you tell me which version of Python.Runtime.NetStandard should be used ? Mine is latest version 3.7.1

**Comment by deepakkumar1984** [comment]
Using 3.6.1.9

**Comment by deepakkumar1984** [comment]
Keras is supported for Python 3.6, so need to use Numpy 3.6.*.*, Are you able to test it?

**Comment by User2587** [comment]
There is no Numpy 3.6 ... I'm still getting the same runtime error for Flatten()

**Comment by deepakkumar1984** [comment]
Are you still facing issue with numpy 3.6

**Comment by User2587** [comment]
Hi, sorry for the late reply. Currently I have dropped down this package and I don't have time to check but I may use it in future, so I'm closing this issue.
