### ISSUE TITLE
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by dsimeonov140** [SciSharp/Keras.NET#53]
Hi,

I get error:
 Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference

In this line:
`var es = new EarlyStopping(monitor: "val_loss", mode: "min", restore_best_weights: true);`

StackTrace:
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Keras.Callbacks.EarlyStopping..ctor(String monitor, Single min_delta, Int32 patience, Int32 verbose, String mode, Nullable`1 baseline, Boolean restore_best_weights)
  

I am using Keras.NET 3.6.1.11

**Comment by csharparun** [comment]
Please check all the parameters are correct, ensure there are no typos.
and passing all the required parameters to the constructor.

**Comment by dsimeonov140** [comment]
Since there are no required parameters in constructor, I tried without parameters, same error. I tried with all possible parameters, same error (I rewrote all the parameters, to ensure there are no typos).

**Comment by dsimeonov140** [comment]
if that matters I have python 3.6.8 installed with this on it:
absl-py==0.8.1
astor==0.8.0
gast==0.2.2
google-pasta==0.1.7
grpcio==1.24.1
h5py==2.10.0
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
numpy==1.17.3
opt-einsum==3.1.0
protobuf==3.10.0
PyYAML==5.1.2
scipy==1.3.1
six==1.12.0
tensorboard==2.0.0
tensorflow==2.0.0
tensorflow-estimator==2.0.1
termcolor==1.1.0
Werkzeug==0.16.0
wrapt==1.11.2

**Comment by dominic7125** [comment]
I have the same issue here.
I've also tried other callback functions, all of them have the same exception raised.

**Comment by deepakkumar1984** [comment]
Fixed in latest version
