### ISSUE TITLE
ValueError : Error when checking input: expected input_1 to have shape (299, 299, 3) but got array with shape (224, 224, 3)

### ISSUE THREAD

**Issue by bigswede74** [SciSharp/Keras.NET#54]
I'm trying to run the examples and when I'm running the ImageRecognition example I'm getting the below error. I have not made any changes to the example code.

ValueError : Error when checking input: expected input_1 to have shape (299, 299, 3) but got array with shape (224, 224, 3).

**Comment by deepakkumar1984** [comment]
Thanks for fixing this. Closing the issue
