### ISSUE TITLE
Running model predict with multiple inputs

### ISSUE THREAD

**Issue by shappy** [SciSharp/Keras.NET#58]
Hi,

I am trying to run predict with a multiple input model.
The API documentation states "The input data, as a Numpy array (or list of Numpy arrays if the model has multiple inputs)."

How do I create this list of numpy arrays?

List<NDarray> arrays = new List<NDarray>(2);
arrays.Add(data1);
arrays.Add(data2);
var y = m.Predict(arrays, 1, 0); // Does not work bc it cannot convert the type

NDarray nd = np.array(arrays)
var y = m.Predict(nd , 1, 0); // Does not work bc it sees this as one array and not a list

**Comment by henon** [comment]
basically you need to go into the implementation of the Predict function and make sure it calls into Python with the right parameters. Maybe you need to add an overload for Predict with List<NDArray> as parameters for that alternative use case. I know this kind of problem from working on Numpy.NET but I don't know exactly what Python expects in your case. You need to experiment a little bit. My guess is that creating a PyTuple of NDArrays could work. What do you say @deepakkumar1984 ?

**Comment by deepakkumar1984** [comment]
@henon I think so too. Will try to run the sample and let you know... Thanks

**Comment by shappy** [comment]
Thanks guys, appreciate the help

**Comment by shappy** [comment]
Hi guys. 
Is there anything you've seen that may help?

I tried to overload the function and input a pytuple to the invoking like so:


        public NDarray Predict(List<NDarray> x, int? batch_size = null, int verbose = 1, int? steps = null, Callback[] callbacks = null)
        {

            var args = new Dictionary<string, object>();

            PyObject[] items = new PyObject[x.Count];
            for (int i=0;i<x.Count;i++)
            {
                items[i] = PyObject.FromManagedObject(x[i]);
            }
            PyTuple x_tuple = new PyTuple(items);

            args["x"] = x_tuple;
            args["batch_size"] = batch_size;
            args["verbose"] = verbose;
            args["steps"] = steps;
            args["callbacks"] = callbacks != null ? callbacks : null;

            return new NDarray(InvokeMethod("predict", args));
        }

But I get error 'object of type 'Shape' has no len()'. Any help would be so awesome

**Comment by henon** [comment]
first of all, I believe you should do `items[i]=x[i].PyObject` instead. I don't know where your error comes from, but this might change a lot.

**Comment by shappy** [comment]
> first of all, I believe you should do `items[i]=x[i].PyObject` instead. I don't know where your error comes from, but this might change a lot.

Amazing, this did the trick. Thank you so much for taking the time to save me time. 
Just to confirm I managed to overload the function and have multiple inputs to my network using this method

**Comment by henon** [comment]
Can you please submit a pull request so the community can profit from this fix?
