### ISSUE TITLE
follow the steps or example but crash

### ISSUE THREAD

**Issue by maochaokuo** [SciSharp/Keras.NET#6]
Hi there:

I try to clone this repository, or follow the steps from readme.md. They both crash with the following messages:

C:\Program Files\dotnet\dotnet.exe (process 8912) exited with code -1073741795.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

Is there any further hint for me to resolve it? Thanks

**Comment by deepakkumar1984** [comment]
Which example project you running? Can you please take the latest and run the basic example which should work fine.

**Comment by maochaokuo** [comment]
hi there:

It does not matter which example (including Basic, Image, Text, and a
complete empty new project with XOR sample). They all crash at the line:

var model = new Sequential();

I guess the problem might concern my environment. I did:

   1. download and install dotnet core 2.2
   2. install anaconda (default with python 3.7)
   3. install python 3.6.8 and update path
   4. install numpy

If possible, please give me recommended process to setup the developing
environment. A few environment verification steps will be appreciated.


Regards,

Thomas Mao

**Comment by henon** [comment]
We know that Pythonnet (which we use to access Python) does not find Python with an Anaconda install. It works with a normal Python installation, that can be said. 
If you could clone the [Pythonnet repo](https://github.com/pythonnet/pythonnet) from source and execute the example on their main readme you should get the same error. Then if you will, please try setting the path right until it works with Anaconda. We then have to discuss how to support Anaconda (automatically, or via manual steps).

**Comment by maochaokuo** [comment]
No, I just clean my environment and reinstall Python 3.6.8. The problem is still the same.

**Comment by henon** [comment]
does the sample from the pythonnet readme work for you? if not when you single step, where does it fail? what message?

**Comment by maochaokuo** [comment]
Hi

How do I specify which virtual environment which I wish to use? in
Keras.net? Thanks


Regards,

Thomas Mao

**Comment by deepakkumar1984** [comment]
Can you try setting the Python.Runtime.PythonEngine.PythonPath and Python.Runtime.PythonEngine.PythonHome to the virtual env directory?

**Comment by maochaokuo** [comment]
When I tried to set either one of the two variables, I got the following error:
```
Unable to load DLL 'python36' or one of its dependencies; The specified module could not be found.
```

**Comment by deepakkumar1984** [comment]
I never tested with virtual environment, will give a try and let you know if its supported or not.

**Comment by adnanlanewla** [comment]
> When I tried to set either one of the two variables, I got the following error:
> 
> ```
> Unable to load DLL 'python36' or one of its dependencies; The specified module could not be found.
> ```

I am getting the exact same error. Spent two days on trying to fix this error.

I set my PythonHome and PythonPath same as my anaconda virtual env (C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64)

**Comment by itzukah** [comment]
Same problem. I have already installed python3.6.8 win64 and python 3.7
![image](https://user-images.githubusercontent.com/51436125/64056572-c294b700-cbc6-11e9-836f-50198533d655.png)

![image](https://user-images.githubusercontent.com/51436125/64056679-b4936600-cbc7-11e9-9174-938e3cc73401.png)

**Comment by philvanzu** [comment]
Trying to load a trained keras model file to make predictions here. 

I think I found a solution to make my miniconda environment work, but then I crash on the next line because Keras module is not found, I imagine that's because I installed tensorflow 2.0 rc1 in that environment and keras is no longer its own thing, it is tensorflow.keras now. Anyway the "Python36.dll not found" crash is resolved for me after this. 
```
            string envPythonHome = "C:\\Users\\username\\Miniconda3\\envs\\tensorflow\\";
            string envPythonLib = envPythonHome + "Lib;" + envPythonHome + "Lib\\site-packages";
            Environment.SetEnvironmentVariable("PYTHONHOME", envPythonHome, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PATH", envPythonHome + ";" + Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.Machine), EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONPATH", envPythonLib, EnvironmentVariableTarget.Process);

            PythonEngine.PythonHome = envPythonHome;
            PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH");`
```
 I wonder if I should try to bypass keras.net and try my luck with pythonnet embedding. I  would just have to execute a few python lines and the necessary imports.

**Comment by deepakkumar1984** [comment]
Can I close this issue?

**Comment by philvanzu** [comment]
Not my issue originally, I was just providing a possible fix for it.

**Comment by deepakkumar1984** [comment]
I know dear :), I was asking the original requester

**Comment by deepakkumar1984** [comment]
Closing this issue, please reopen if still having the problem
