### ISSUE TITLE
Default parameter string sample_weight_mode should be null, not "None" for public void Compile in class BaseModel

### ISSUE THREAD

**Issue by torbjornmolin** [SciSharp/Keras.NET#67]
When running the TextExamples I got an asser error from training.py on line 3134 assert sample_weight_mode in ['temporal', 'samplewise'].
This was because the contition for the if-statement above it was not true:
`if (sample_weight is None and
        (self.should_skip_target_weights() or sample_weight_mode is None or
         context.executing_eagerly())):
      self._sample_weight = None
      return`
sample_weight_mode was the string "None", not None. Changing the default parameter  string sample_weight_mode of BaseModel.Compile to null solved the issue for me.

**Comment by deepakkumar1984** [comment]
Can you PR?

**Comment by torbjornmolin** [comment]
I'm a bit confused by the way issues work on github, but this one was solved with PR #68 that I created.
