### ISSUE TITLE
ASP.NET

### ISSUE THREAD

**Issue by estruch** [SciSharp/Keras.NET#7]
Is it possible to use Keras.NET embedded into an ASP.NET application?

**Comment by estruch** [comment]
I tried it and an exception occurs:

[PythonException: AttributeError : 'NoneType' object has no attribute 'write']
   Python.Runtime.Runtime.CheckExceptionOccurred() +55
   Python.Runtime.PythonEngine.ImportModule(String name) +18
   Keras.Keras.InstallAndImport(String module) +71
   Keras.<>c.<.cctor>b__14_0() +55
   System.Lazy`1.CreateValue() +708
   System.Lazy`1.LazyInitValue() +184
   Keras.Models.Sequential..ctor() +467
   EE.Web.Portal.Controllers.<Train>d__7.MoveNext() in D:\Usuarios\Toni\Source\Workspaces\EE\Master\EE.Web.Portal\Controllers\PrediccionesMedidasController.cs:153
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31

**Comment by deepakkumar1984** [comment]
Do you have Python 3.6 and keras installed with one of the backend (Tensorflow/CNTK/PlaidML)?

**Comment by estruch** [comment]
I only used a simple:

var model = new Sequential();

**Comment by deepakkumar1984** [comment]
Keras.NET is a C# binding of Keras python framework. It's not a pure C# implementation. Do you have Python 3.6 and keras installed with one of the backend (Tensorflow/CNTK/PlaidML)?

**Comment by estruch** [comment]
Yes, i have all of them installed, and "BasicSamples" project works correctly (No Web App).
I am trying now to execute XOR.cs sample code inside a simple MVC action and fails (Web App inside IIS running as same user account that executed correctly Python, Keras, etc).

**Comment by deepakkumar1984** [comment]
I haven't really tested with ASP.NET. Traning a model using Web Framework is not a good idea since it will be a long running job and the IIS will timeout breaking the session. Anyhow possible to share the code so that I can try to reproduce in my system?

**Comment by estruch** [comment]
Here we go ...

[KerasASP.NET.zip](https://github.com/SciSharp/Keras.NET/files/3400294/KerasASP.NET.zip)

If you run this against to IIS, fails on new Sequential
If you run this against to IISExpress (x64), fails on Fit

Both are running as user account that executes correctly python and keras

**Comment by deepakkumar1984** [comment]
Since pythonnet is built with .net standard, so I have moved the project to Asp.net core. Attached the project:
[KerasASP.NET.zip](https://github.com/SciSharp/Keras.NET/files/3415736/KerasASP.NET.zip)

Other issue is using verbose which will not work in IIS and only works if using .net core kestrel, maybe the cause of logging which need access to console. I would prefer .net core kestrel since you can then deploy to Linux as well.

**Comment by estruch** [comment]
Ok. I'll try to port the solution to .net core and execute it using kestrel.
Thanks.
