### ISSUE TITLE
BaseModel.fit: class_weight => System.NotImplementedException: 'Type is not yet supported: Dictionary`2. Add it to 'ToPythonConversions''

### ISSUE THREAD

**Issue by nix4332** [SciSharp/Keras.NET#72]
When calling the Fit-Method for a sequential model I try to assign class-weights for imbalanced classes like so:

```
var dctClassWeights = new Dictionary<int, float>();
dctClassWeights.Add(0, 0.2f);
dctClassWeights.Add(1, 0.3f);
dctClassWeights.Add(2, 0.5f);

model.Fit(x_train, y_train

       , class_weight: dctClassWeights  

);
```

Unfortunately this results in the following exception:

**System.NotImplementedException: 'Type is not yet supported: Dictionary`2. Add it to 'ToPythonConversions''**

How can I correct that ? Am I missing something here ?

Thank you
Andrew

**Comment by deepakkumar1984** [comment]
Fixed with latest version.
