### ISSUE TITLE
 When I used new Sequential to create a model, I found that I could only train it once, and it kept running the second time, and it stuck here. How to train the model multiple times?

### ISSUE THREAD

**Issue by FrankZhou-jun** [SciSharp/Keras.NET#75]
code like this
......
Sequential model = new Sequential();
 model = cnnmodel.LoadModel(model,layerParam);
g_saveModelPara_CNN=cnnmodel.RunCNN(txt_modelfilePath.Text.Trim(), txt_trainFileName.Text.Trim(), txt_testFileName.Text.Trim(), model, modelTrainModel_CNN_Params);
......

**Comment by deepakkumar1984** [comment]
May be you can post complete code to dubug. Won't be able to help with the above.

**Comment by FrankZhou-jun** [comment]
Thank you for your reply. The previous stutter at new Sequential was because I ran this code in a new thread. If I haven't opened a thread, I recently discovered that I can repeat the training.

     private void trainCNNmodel()
        {
            if (txt_trainFileName.Text.Trim() == null || txt_testFileName.Text.Trim() == null)
            {
                MessageBox.Show("请选择测试集或训练集文件", "提示", MessageBoxButtons.OK);
                return;

            }

            if (Path.GetDirectoryName(txt_trainFileName.Text.Trim()) != Path.GetDirectoryName(txt_testFileName.Text.Trim()))
            {
                MessageBox.Show("训练集或测试集应该置于同一文件夹下", "提示", MessageBoxButtons.OK);
                return;

            }

            if (txt_modelfilePath.Text == null)
            {
                MessageBox.Show("请选择训练模型文件", "提示", MessageBoxButtons.OK);
                return;
            }

            if (txt_modelfilePath.Text.Trim()== null)
            {
                MessageBox.Show("未打开模型文件", "提示", MessageBoxButtons.OK);
                return;
            }
             #it could repeat the training in this way
            if (!g_flag_isTraining)
            {
                thread_trainCNN();
                g_flag_isTraining = false;
            }

             #Stuck in this way
            //if (gx == null || !gx.IsAlive)
            //{
            //    //set a new thread for dealing with training process
            //    ThreadStart xstart = new ThreadStart(thread_trainCNN);
            //    Thread x = new Thread(xstart);
            //    x.Name = "trian_thread";
            //    gx = x;
            //    x.IsBackground = true;//this thread will close when the main thread is close
            //    x.Start();
            //}
        }

        private void thread_trainCNN()
        {
            g_sum = 0;
            g_flag_isTraining = true;
            #region 超参数
            int epochs = 1;
            double learningrate = 0.032;
            uint minibatchSize = 1;
            double validSplit = 0.3;

            //get the value of epoches,batchNumber,learningRate,PrintFreq
            SaveModelPara_CNN.ModelTrainModel_CNN_Params modelTrainModel_CNN_Params = new SaveModelPara_CNN.ModelTrainModel_CNN_Params(g_dataTableCnnParams);
            learningrate = modelTrainModel_CNN_Params.ParaValue1_epoch;
            epochs =(int) modelTrainModel_CNN_Params.ParaValue2_batchSize;
            minibatchSize = Convert.ToUInt32(modelTrainModel_CNN_Params.ParaValue3_lr);
            validSplit = modelTrainModel_CNN_Params.ParaValue4_Validation_split;
            #endregion

            BLLKearsModel.CNN_model cnnmodel = new BLLKearsModel.CNN_model();
            Dictionary<string, CModelConstructModel_CNN> layerParam = BLL.CCnnClassifier.ReadMdoelParam("CNN", txt_modelfilePath.Text);

            Sequential model = null; 
            model = new Sequential();
         
            model = cnnmodel.LoadModel(model,layerParam);

            g_saveModelPara_CNN=cnnmodel.RunCNN(txt_modelfilePath.Text.Trim(), txt_trainFileName.Text.Trim(), txt_testFileName.Text.Trim(), model, modelTrainModel_CNN_Params);


            //显示准确率曲线
            //clear txt_printOut data
            chart_cnnWaveForm.BeginInvoke(new Action(() =>
            {
                for (int j = 0; j < chart_cnnWaveForm.Series.Count; j++)
                {
                    InitSeries();
                    chart_cnnWaveForm.Series[j].XValueMember=String.Empty;
                    chart_cnnWaveForm.Series[j].YValueMembers = String.Empty;

                }
            }));

            //upata the data of chart
            NDarray epoches=(NDarray)g_saveModelPara_CNN.epochArray;
            for (int i=0;i< epoches.len;i++)
            {
                object[] para = new object[3];
                para[0] = this.chart_cnnWaveForm;
                para[1] =((NDarray)g_saveModelPara_CNN.trainAccArray)[i].ToString();
                para[2] = ((NDarray)g_saveModelPara_CNN.validAccArray)[i].ToString();

                this.BeginInvoke(new MyChartDelegate(AddDataToSerile), para);

            }
            btn_OverView_Click(null, null);
            string trainacc = ((NDarray)g_saveModelPara_CNN.trainAccArray)[(int)modelTrainModel_CNN_Params.ParaValue1_epoch - 1].ToString();
            string validacc = ((NDarray)g_saveModelPara_CNN.validAccArray)[(int)modelTrainModel_CNN_Params.ParaValue1_epoch - 1].ToString();

            txt_printOut.Text = string.Format("训练集准确率:{0},验证集准确率:{1}", trainacc, validacc);
            g_flag_trainIsFinish = true ;
            
        }

**Comment by zaqxs123456** [comment]
I have the same problem, I try to run it on Unity. It run fine at the first time, but the second time it crash. I used the XOR demo to test, so it seem not the problem about the code. 

Maybe I have to clear cache or something like that?

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;
using Numpy;
using Keras.Models;
using Keras.Layers;
using Keras;

public class Test : MonoBehaviour
	{
	void Start()
		{
		//Load train data
		NDarray x = np.array(new float[,] { { 0, 0 }, { 0, 1 }, { 1, 0 }, { 1, 1 } });
		NDarray y = np.array(new float[] { 0, 1, 1, 0 });

		//Build sequential model
		var model = new Sequential();
		model.Add(new Dense(32, activation: "relu", input_shape: new Shape(2)));
		model.Add(new Dense(64, activation: "relu"));
		model.Add(new Dense(1, activation: "sigmoid"));

		//Compile and train
		model.Compile(optimizer: "sgd", loss: "binary_crossentropy", metrics: new string[] { "accuracy" });
		model.Fit(x, y, batch_size: 2, epochs: 1000, verbose: 1);

		//Save model and weights
		string json = model.ToJson();
		File.WriteAllText("model.json", json);
		model.SaveWeight("model.h5");

		//Load model and weight
		var loaded_model = Sequential.ModelFromJson(File.ReadAllText("model.json"));
		loaded_model.LoadWeight("model.h5");
		}
	}
```
