### ISSUE TITLE
More Defensive Coding Needed

### ISSUE THREAD

**Issue by Nodice** [SciSharp/Keras.NET#79]
Thanks so much for Writing Keras.NET!

Keras.cs has a minor flaw.

_instance should be handling it's caught errors better.

instance.keras2onnx = InstallAndImport("onnxmltools");
and
instance.tfjs = InstallAndImport("tensorflowjs");

Should be throwing Console.Writelines.

No details on the read me show that onnxmltools or tensorflowjs modules are needed and on Keras.Run it will also not install those two modules.

I recommend edits to those two instance variables and change the install script as well as mention it on the read me.

I would make the edits, but i've actually never submitted a git!

**Comment by deepakkumar1984** [comment]
Thanks for your help!
