### ISSUE TITLE
 When I have been training the DQN model, the memory keeps soaring. Is there any way to solve it?  Where is the problem？The code is as follows:

### ISSUE THREAD

**Issue by FrankZhou-jun** [SciSharp/Keras.NET#81]
while (!done)
                {
                    List<double> action=new List<double>(agent.n_actions);
                    List<double> reward=new List<double>(1);

                    DisposeNdArgs.DisposAction DisposeAction = agent.choose_action(observation,out action);
                    DisposeAction.DisposActionInvok();

                    env.step(action, t_steps % trainN, modelTrainModel_DQN_Params.ParaValue8_rewardValue,
                        modelTrainModel_DQN_Params.ParaValue9_penaltyValue, out observation_, out reward, out done);

                    agent.store_transition(observation, action, reward, observation_);
                    allReward.Add(reward[0]);

                    if(agent.memeries_list.Count < agent.n_expericePool)
                        Console.WriteLine("已有{0}经验样本", agent.memeries_list.Count);

                    if (agent.memeries_list.Count >=agent.n_expericePool)
                    {
                        DisposeNdArgs.DisposLearning eventArgs =agent.learning();
                        eventArgs.DisposLearningInvok();

                    }

                    observation = observation_;
                    ++t_steps;
                }

      
      **//The model fit is as follows**
      public DisposeNdArgs.DisposLearning learning()
            {

                if (n_learn_step_counter % n_replace_target_iter == 0)
                {
                    q_next_modle.SetWeights(q_eval_modle.GetWeights());
                    Console.WriteLine("已更新目标量网络参数");
                }

                List<SmemerySample> batch_memory_list = zjMethods.ListRandomSamole(memeries_list, n_expericePool,n_expericeSamples);

                NDarray Nds_array = np.zeros(s_shape_Input);
                NDarray Nda_array = np.zeros(a_shape_Input);
                NDarray Ndr_array = np.zeros(r_shape_Input);
                NDarray Ndnext_s_array = np.zeros(s_shape_Input);
                NDarray Ndq_next;
                NDarray Ndq_eval;
                NDarray Ndq_target;
                NDarray Ndbatch_index;
                NDarray Ndeval_act_index;
                NDarray Ndselected_q_next;
                NDarray Nddelt_act_max;
                Keras.Callbacks.History Ndhistory;
                NDarray NdcostArray;
                NDarray Ndcost;

                int i = 0;
                foreach (var item in batch_memory_list)
                {

                    Nds_array[i]=np.array(item.s.ToArray()).reshape(s_shape_single);
                    Nda_array[i] = np.array(item.a.ToArray()).reshape(a_shape_single);
                    Ndr_array[i] = np.array(item.r.ToArray()).reshape(r_shape_single);
                    Ndnext_s_array[i] = np.array(item.s_.ToArray()).reshape(s_shape_single);
                    i++;

                }
            
                 Ndq_next = q_next_modle.Predict(x: Ndnext_s_array);
                 Ndq_eval = q_eval_modle.Predict(x: Ndnext_s_array);
                 Ndq_target = Ndq_eval.copy();

                 Ndbatch_index = np.arange(modelTrainModel_DQN_Params.ParaValue4_expericeSample, dtype: np.int32);

                 Ndeval_act_index = np.argmax(Nda_array, axis: 1).astype(np.int32);

                 Ndselected_q_next = np.max(Ndq_next, axis: new int[] { 1 });

                
                 Nddelt_act_max = (1 - modelTrainModel_DQN_Params.ParaValue6_qlearningRate) * Ndq_eval[Ndbatch_index, Ndeval_act_index];
                 Ndq_target[Ndbatch_index, Ndeval_act_index] = Nddelt_act_max + modelTrainModel_DQN_Params.ParaValue6_qlearningRate * (np.squeeze(Ndr_array) + gamma * Ndselected_q_next);

        

                Ndhistory = q_eval_modle.Fit(x: Nds_array, y: Ndq_target, verbose: 0);

                 NdcostArray = np.array(Ndhistory.HistoryLogs["loss"]);
                 Ndcost = np.around(NdcostArray[-1], 4);
               

                n_learn_step_counter += 1;

                DisposeNdArgs.DisposLearning disposLearning =new DisposeNdArgs.DisposLearning(
                Nds_array,
                Nda_array,
                Ndr_array,
                Ndnext_s_array,
                Ndq_next,
                Ndq_eval,
                Ndq_target,
                Ndbatch_index,
                Ndeval_act_index,
                Ndselected_q_next,
                Nddelt_act_max,
                Ndhistory,
                NdcostArray,
                Ndcost);

                return disposLearning;
            }

**Comment by deepakkumar1984** [comment]
Ok I will look into it. Seems like some objects are not getting disposed

**Comment by FrankZhou-jun** [comment]
ok,thank you for your time

**Comment by Nodice** [comment]
I don't see any queue depth logic in the pasted code, but maybe i'm just not seeing it.

If your not trimming your experience queue that can just keep filling up.
I also can't see the data type on the pasted code. If you are using Bitmaps, .NET is notorious for not disposing.

If you can check your code into a repository i can take a look as well.

**Comment by FrankZhou-jun** [comment]
Using MNIST data, it is found that memory is still rising. I have uploaded the complete code to my [repository,](https://github.com/FrankZhou-jun/test_DQN/blob/master/code) .if you have time to review it, I would appreciate it.

**Comment by eduardobellotto** [comment]
I'm having the same problem with TrainOnBatch method
