### ISSUE TITLE
Scoring ,Predicting in .net

### ISSUE THREAD

**Issue by kiranmaya** [SciSharp/Keras.NET#88]
Training keras.net work fine in c# environment using python back-end .,but for scoring [predicting] with model is not ideal,very very slow ,and i need to have multi threading ,  
my data is 120 columns of float input, and model graph is around 10 million weights neural network graph.
i followed these steps
1 training with keras.net
2 exporting onnx model 
3 - stuck here ,tried https://www.nuget.org/packages/Microsoft.ML.Scoring/ , not working .
is there any other way ,to consume keras.net exportable models in pure standlone .net without anything related to python .
what are my options here .
Thanks

**Comment by deepakkumar1984** [comment]
Have you tried this one: https://github.com/microsoft/onnxruntime/blob/master/docs/CSharp_API.md#getting-started

**Comment by deepakkumar1984** [comment]
Closign as there is no comments.
