### ISSUE TITLE
ModuleNotFoundError No module named numpy

### ISSUE THREAD

**Issue by maochaokuo** [SciSharp/Keras.NET#9]
I tried to run BasicSamples project. I got the 
```
Python.Runtime.PythonException: 'ModuleNotFoundError: No module named 'numpy' 
```
error message, at the line:
```

    public class XOR
    {
        public static void Run()
        {
            //Load train data
            NDarray x = np.array(new float[,] { { 0, 0 }, { 0, 1 }, { 1, 0 }, { 1, 1 } });
.........................
```
I am not sure whether this may relate to 
```
follow the steps or example but crash (#6)
```
or not. The difference is that, this happen to another computer, in which there is only one Python environment.

**Comment by deepakkumar1984** [comment]
Please install numpy using pip install numpy command

**Comment by deepakkumar1984** [comment]
Are you able to run the example?

**Comment by maochaokuo** [comment]
No, I cannot run the example. I reported both #6 and this one.

**Comment by deepakkumar1984** [comment]
I guess its the virtual environment issue which I havent tested. Will let you know after I tested the support for it

**Comment by wy9884255** [comment]
@maochaokuo  check PythonEngine.PythonPath in keras.cs to ensure it points your default python venv which numpy and tensorflow.keras has been installed

**Comment by deepakkumar1984** [comment]
Are you still facing issue?

**Comment by maochaokuo** [comment]
No, I do not have time to try it. You may ignore me already. Sorry about
that.

Regards,

Thomas Mao

**Comment by deepakkumar1984** [comment]
No problem.  Please create another issue if facing again

**Comment by Deepika021** [comment]
Hi, i am getting same error Python.Runtime.PythonException: 'ModuleNotFoundError : No module named 'keras''. I have installed tensorflow.net still getting error. couldn't run the project.

**Comment by JagathPrasad** [comment]
Hi, I am getting the same error "Python.Runtime.PythonException: 'ModuleNotFoundError : No module named 'numpy''. Unable to run the project.

**Comment by lszlp76** [comment]
Same problem as
Python.Runtime.PythonException: 'ModuleNotFoundError: No module named 'numpy' 

any idea @deepakkumar1984 ?

**Comment by JagathPrasad** [comment]
Please check this medium blog to solve the issue.
https://medium.com/@jagathprasad0/deep-learning-using-keras-net-with-c-1d1fceac4531

**Comment by lszlp76** [comment]
@JagathPrasad thanks a lot. It worked.

**Comment by veeru612** [comment]
Hi, I get the same error when running the example. 
Here is a screenshot of command window:
![image](https://user-images.githubusercontent.com/33726682/108901535-fba9be00-75e8-11eb-8945-be4d33413992.png)

Any ideas on how to get the example working?

Many thanks.
