### ISSUE TITLE
NDarray error initialization inside RestApi method (C#/WebApi project)

### ISSUE THREAD

**Issue by berlicon** [SciSharp/Keras.NET#92]
I have code in my REST API method:
var array = new float[1, 2];
var ndArray = new NDarray(array);//first time OK, 2nd time app hangs on this line :(
result = ndArray.ToString();

It works first time. But on 2nd run app hangs. I try to create and fill NDarray in order to put it as input to Keras model.

How to fix it?

Earlier, I submit this bug to Numpy.net project but no luck this time.
https://github.com/SciSharp/Numpy.NET/issues/26

**Comment by henon** [comment]
I resolved the hanging. It was because of missing setup. Also calls to numpy must be wrapped in `using(Py.GIL()) { ... }`

**Comment by berlicon** [comment]
Bug was fixed. Thank you @henon ! See solution in ticket https://github.com/SciSharp/Numpy.NET/issues/26

The undocumented BUT CRUCIAL PART OF SOLUTION is the line in Program.cs:
// this call initializes numpy. it is necessary to do that before PythonEngine.BeginAllowThreads()
np.arange(1); //!!! MANDATORY LINE
PythonEngine.BeginAllowThreads();

//and code in webapi method:
using (Py.GIL())                    {
                var array = new float[1, 2];
                var ndArray = new NDarray(array);//NO DEADLOCKS THIS LINE! ALL WORKS AS EXPECTED
                result = ndArray.ToString();
                    }
