### ISSUE TITLE
Can not build on pc from source

### ISSUE THREAD

**Issue by ipud2** [SciSharp/Keras.NET#98]
I have installed tensorflow2.0 and kereas.

Python.Runtime.PythonException:“ValueError : Unknown regularizer: ”

**Comment by deepakkumar1984** [comment]
Which version of keras you have?

**Comment by deepakkumar1984** [comment]
Are you still facing issue? Can you please post the code

**Comment by deepakkumar1984** [comment]
Closing as no further comment. Please open another issue if still facing it.
